site_name: Ministry of Health Digital Knowledge Platform
site_description: Ministry of Health digital publications platform
theme:
  name: material
  logo: assets/moh-logo.png
  favicon: assets/moh-logo.png
  font:
    text: Inter
    code: Roboto Mono
  features:

    - navigation.sections
    - content.tabs.link
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
    - navigation.indexes
    - navigation.path
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.instant
plugins:
- search:
    lang: en
    separator: '[\s\-\.]+'
- glightbox
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
       - name: mermaid
         class: mermaid
         format: !!python/name:pymdownx.superfences.fence_code_format
- attr_list
- md_in_html
- toc:
    permalink: true
    toc_depth: 2
nav:
- Knowledge Platform: index.md
- UCG 2023:
  - Introduction & Preface:
    - chapters_split/00/index.md
  - "Chapter 1: Emergencies and Trauma": 
          - chapters_split/01/index.md
  - "Chapter 2: Infectious Diseases": 
          - chapters_split/02/index.md

  - "Chapter 3: HIV/AIDS and Sexually Transmitted Infections":
          - chapters_split/03/index.md
          
  - "Chapter 4: Cardiovascular Diseases":
          - chapters_split/04/index.md

  - "Chapter 5: Respiratory Diseases":
          - chapters_split/05/index.md

  - "Chapter 6: Gastrointestinal and Hepatic Diseases":
          - chapters_split/06/index.md

  - "Chapter 7: Renal and Urinary Diseases":
          - chapters_split/07/index.md

  - "Chapter 8: Endocrine and Metabolic Diseases":
          - chapters_split/08/index.md
          
  - "Chapter 9: Mental, Neurological and Substance Use Disorders":
          - chapters_split/09/index.md

  - "Chapter 10: Musculoskeletal and Joint Diseases":
          - chapters_split/10/index.md

  - "Chapter 11: Blood Diseases and Blood Transfusion Guidelines":
          - chapters_split/11/index.md

  - "Chapter 12: Oncology":
          - chapters_split/12/index.md

  - "Chapter 13: Palliative Care":
          - chapters_split/13/index.md
          
  - "Chapter 14: Gynaecological Conditions":
          - chapters_split/14/index.md
          
  - "Chapter 15: Family Planning (FP)":
          - chapters_split/15/index.md
          
  - "Chapter 16: Obstetric Conditions":
          - chapters_split/16/index.md
          
  - "Chapter 17: Childhood Illness":
          - chapters_split/17/index.md
         
  - "Chapter 18: Immunization":
          - chapters_split/18/index.md
          
  - "Chapter 19: Nutrition":
          - chapters_split/19/index.md
          
  - "Chapter 20: Eye Conditions":
          - chapters_split/20/index.md
         
  - "Chapter 21: Ear, Nose and Throat Conditions":
          - chapters_split/21/index.md
         
  - "Chapter 22: Skin Diseases":
          - chapters_split/22/index.md
         
  - "Chapter 23: Oral and Dental Conditions":
          - chapters_split/23/index.md
          
  - "Chapter 24: Surgery, Radiology and Anaesthesia":
          - chapters_split/24/index.md
         

extra_css:
- stylesheets/extra.css
- assets/css/floating-actions.css
- stylesheets/snake-gallery.css
extra_javascript:
- assets/js/floating-actions.js
