site_name: Ministry of Health Digital Knowledge Platform
site_description: Ministry of Health digital publications platform
theme:
  name: material
  logo: assets/moh-logo.png
  favicon: assets/moh-logo.png
  font:
    text: Inter
    code: Roboto Mono
  features:

    # - navigation.sections
    - content.tabs.link
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
    - navigation.indexes
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
plugins:
- search:
    lang: en
    separator: '[\s\-\.]+'
- glightbox
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- attr_list
- md_in_html
- toc:
    permalink: true
    toc_depth: 4
nav:
- Knowledge Platform: index.md
- UCG 2023:
  - Introduction & Preface:
    - chapters_split/00/index.md
  - "Chapter 1: Emergencies and Trauma": 
          - chapters_split/01/index.md
  - "Chapter 2: Infectious Diseases":
          - chapters_split/02/index.md
          - "2.1 Bacterial Infections": chapters_split/02/2-01-bacterial-infections.md
          - "2.2 Fungal Infections": chapters_split/02/2-02-fungal-infections.md
          - "2.3 Viral Infections": chapters_split/02/2-03-viral-infections.md
          - "2.4 Helminthes Parasites": chapters_split/02/2-04-helminthes-parasites.md
          - "2.5 Protozoal Parasites": chapters_split/02/2-05-protozoal-parasites.md

  - "Chapter 3: HIV/AIDS and Sexually Transmitted Infections":
          - chapters_split/03/index.md
          - "3.1 HIV Infection and Acquired Immunodeficiency Syndrome (AIDS)": chapters_split/03/3-01-hiv-infection-and-acquired-immunodeficiency-syndrome-aids.md
          - "3.2 Sexually Transmitted Infections (STI)": chapters_split/03/3-02-sexually-transmitted-infections-sti.md

  - "Chapter 4: Cardiovascular Diseases":
          - chapters_split/04/index.md
          - "4.1 Cardiovascular Conditions": chapters_split/04/4-01-cardiovascular-conditions.md

  - "Chapter 5: Respiratory Diseases":
          - chapters_split/05/index.md
          - "5.1 Non-Infectious Respiratory Diseases": chapters_split/05/5-01-non-infectious-respiratory-diseases.md
          - "5.2 Infectious Respiratory Diseases": chapters_split/05/5-02-infectious-respiratory-diseases.md
          - "5.3 Tuberculosis (TB)": chapters_split/05/5-03-tuberculosis-tb.md

  - "Chapter 6: Gastrointestinal and Hepatic Diseases":
          - chapters_split/06/index.md
          - "6.1 Gastrointestinal Emergencies": chapters_split/06/6-01-gastrointestinal-emergencies.md
          - "6.2 Gastrointestinal Infections": chapters_split/06/6-02-gastrointestinal-infections.md
          - "6.3 Gastrointestinal Disorders": chapters_split/06/6-03-gastrointestinal-disorders.md
          - "6.4 Anorectal Disorders": chapters_split/06/6-04-anorectal-disorders.md
          - "6.5 Hepatic and Biliary Diseases": chapters_split/06/6-05-hepatic-and-biliary-diseases.md

  - "Chapter 7: Renal and Urinary Diseases":
          - chapters_split/07/index.md
          - "7.1 Renal Diseases": chapters_split/07/7-01-renal-diseases.md
          - "7.2 Urological Diseases": chapters_split/07/7-02-urological-diseases.md

  - "Chapter 8: Endocrine and Metabolic Diseases":
          - chapters_split/08/index.md
          - "8.1 Endocrine and Metabolic Conditions": chapters_split/08/8-01-endocrine-and-metabolic-conditions.md

  - "Chapter 9: Mental, Neurological and Substance Use Disorders":
          - chapters_split/09/index.md
          - "9.1 Neurological Disorders": chapters_split/09/9-01-neurological-disorders.md
          - "9.2 Psychiatric and Substance Use Disorders": chapters_split/09/9-02-psychiatric-and-substance-use-disorders.md

  - "Chapter 10: Musculoskeletal and Joint Diseases":
          - chapters_split/10/index.md
          - "10.1 Infectious Musculoskeletal Conditions": chapters_split/10/10-01-infectious-musculoskeletal-conditions.md
          - "10.2 Inflammatory/Degenerative Disorders": chapters_split/10/10-02-inflammatory-degenerative-disorders.md

  - "Chapter 11: Blood Diseases and Blood Transfusion Guidelines":
          - chapters_split/11/index.md
          - "11.1 Blood Diseases": chapters_split/11/11-01-blood-diseases.md
          - "11.2 Blood and Blood Products": chapters_split/11/11-02-blood-and-blood-products.md

  - "Chapter 12: Oncology":
          - chapters_split/12/index.md
          - "12.1 Cancer Recognition and Risk": chapters_split/12/12-01-cancer-recognition-and-risk.md
          - "12.2 Prevention of Cancer": chapters_split/12/12-02-prevention-of-cancer.md
          - "12.3 Common Cancers": chapters_split/12/12-03-common-cancers.md

  - "Chapter 13: Palliative Care":
          - chapters_split/13/index.md
          - "13.1 Pain": chapters_split/13/13-01-pain.md
          - "13.2 Other Conditions in Palliative Care": chapters_split/13/13-02-other-conditions-in-palliative-care.md

  - "Chapter 14: Gynaecological Conditions":
          - chapters_split/14/index.md
          - "14.1 Gynaecological Conditions": chapters_split/14/14-01-gynaecological-conditions.md

  - "Chapter 15: Family Planning (FP)":
          - chapters_split/15/index.md
          - "15.1 Family Planning Service Provision": chapters_split/15/15-01-family-planning-service-provision.md
          - "15.2 Overview of Key Contraceptive Methods": chapters_split/15/15-02-overview-of-key-contraceptive-methods.md

  - "Chapter 16: Obstetric Conditions":
          - chapters_split/16/index.md
          - "16.1 Antenatal Care": chapters_split/16/16-01-antenatal-care.md
          - "16.2 Management of Selected Conditions in Pregnancy": chapters_split/16/16-02-management-of-selected-conditions-in-pregnancy.md
          - "16.3 Antenatal Complications": chapters_split/16/16-03-antenatal-complications.md
          - "16.4 Labour, Delivery and Acute Complications": chapters_split/16/16-04-labour-delivery-and-acute-complications.md
          - "16.5 Essential Care of the Newborn": chapters_split/16/16-05-essential-care-of-the-newborn.md
          - "16.6 Postpartum Conditions": chapters_split/16/16-06-postpartum-conditions.md
          - "16.7 Intrauterine Fetal Demise (IUFD) or Fetal Death": chapters_split/16/16-07-intrauterine-fetal-demise-iufd-or-fetal-death.md

  - "Chapter 17: Childhood Illness":
          - chapters_split/17/index.md
          - "17.1 Newborn and Young Infant Assessment": chapters_split/17/17-01-newborn-and-young-infant-assessment.md
          - "17.2 Sick Young Infant Age Up to 2 Months": chapters_split/17/17-02-sick-young-infant-age-up-to-2-months.md
          - "17.3 Sick Child Age 2 Months to 5 Years": chapters_split/17/17-03-sick-child-age-2-months-to-5-years.md
          - "17.4 Integrated Community Case Management": chapters_split/17/17-04-integrated-community-case-management.md
          - "17.5 Child Growth Weight Standards Charts": chapters_split/17/17-05-child-growth-weight-standards-charts.md

  - "Chapter 18: Immunization":
          - chapters_split/18/index.md
          - "18.1 Immunization and Vaccination": chapters_split/18/18-01-immunization-and-vaccination.md
          - "18.2 Special Immunization Considerations": chapters_split/18/18-02-special-immunization-considerations.md

  - "Chapter 19: Nutrition":
          - chapters_split/19/index.md
          - "19.1 Nutrition in Special Conditions": chapters_split/19/19-01-nutrition-in-special-conditions.md
          - "19.2 Malnutrition": chapters_split/19/19-02-malnutrition.md

  - "Chapter 20: Eye Conditions":
          - chapters_split/20/index.md
          - "20.1 Common Eye Conditions": chapters_split/20/20-01-common-eye-conditions.md
          - "20.2 Decreased or Reduced Vision Conditions": chapters_split/20/20-02-decreased-or-reduced-vision-conditions.md
          - "20.3 Trauma and Injuries to the Eye": chapters_split/20/20-03-trauma-and-injuries-to-the-eye.md
          - "20.4 Ocular Tumours": chapters_split/20/20-04-ocular-tumours.md

  - "Chapter 21: Ear, Nose and Throat Conditions":
          - chapters_split/21/index.md
          - "21.1 Ear Conditions": chapters_split/21/21-01-ear-conditions.md
          - "21.2 Nasal Conditions": chapters_split/21/21-02-nasal-conditions.md
          - "21.3 Throat Conditions": chapters_split/21/21-03-throat-conditions.md

  - "Chapter 22: Skin Diseases":
          - chapters_split/22/index.md
          - "22.1 Bacterial Skin Infections": chapters_split/22/22-01-bacterial-skin-infections.md
          - "22.2 Viral Skin Infections": chapters_split/22/22-02-viral-skin-infections.md
          - "22.3 Fungal Skin Infections": chapters_split/22/22-03-fungal-skin-infections.md
          - "22.4 Parasitic Skin Infections": chapters_split/22/22-04-parasitic-skin-infections.md
          - "22.5 Inflammatory and Allergic Skin Conditions": chapters_split/22/22-05-inflammatory-and-allergic-skin-conditions.md
          - "22.6 Skin Ulcers and Chronic Wounds": chapters_split/22/22-06-skin-ulcers-and-chronic-wounds.md
          - "22.7 Drug-Induced Skin Reactions": chapters_split/22/22-07-drug-induced-skin-reactions.md
          - "22.8 Congenital Disorder": chapters_split/22/22-08-congenital-disorder.md

  - "Chapter 23: Oral and Dental Conditions":
          - chapters_split/23/index.md
          - "23.1 Oral and Dental Assessment": chapters_split/23/23-01-oral-and-dental-assessment.md
          - "23.2 Oro-Dental Infections": chapters_split/23/23-02-oro-dental-infections.md
          - "23.3 HIV/AIDS Associated Conditions": chapters_split/23/23-03-hiv-aids-associated-conditions.md
          - "23.4 Oral Trauma": chapters_split/23/23-04-oral-trauma.md
          - "23.5 Oral Tumours": chapters_split/23/23-05-oral-tumours.md

  - "Chapter 24: Surgery, Radiology and Anaesthesia":
          - chapters_split/24/index.md
          - "24.1 Surgery": chapters_split/24/24-01-surgery.md
          - "24.2 Diagnostic Imaging": chapters_split/24/24-02-diagnostic-imaging.md
          - "24.3 Anaesthesia": chapters_split/24/24-03-anaesthesia.md

- Integrated Child Health Days Implementation Guide: resources/clinical-guidelines/ICHDS_guideline_final.md
- Essential Maternal and Newborn Care Guidelines 2022: resources/mnch-srh/Essential_Maternal_Newborn_Care_Guidelines_2022_V3.md
- Goal-Oriented Antenatal Care Protocol: resources/mnch-srh/Goal_Oriented_ANC_protocol.md
- Weekly Epidemiological Bulletin, Week 46, 2019: resources/disease-programmes-surveillance/week_46_2019.md
- Weekly Executive Brief, Week 35: resources/disease-programmes-surveillance/Weekly_Executive_Brief_wk35.md
- Health Information and Digital Health Strategic Plan: resources/health-education-service-delivery/Health_Information_Digital_Health_Strategic_Plan.md
- Standard Operating Procedures for Health Information: resources/health-education-service-delivery/Standard_Operating_Procedures_for_Health_Information_2010.md
- A Brief Guide to iHRIS Qualify: resources/health-education-service-delivery/A_Brief_Guide_to_iHRIS_Qualify.md
- Routine Client Satisfaction Feedback Guidelines: resources/health-education-service-delivery/Routine_Client_Satisfaction_Feedback_Guidelines_June_2024_Fnal.md
- Routine Client Satisfaction Survey QR Code: resources/health-education-service-delivery/Routine_Client_Satisfaction_Survey_QR_Code.md
- Progress Reports Variety: resources/health-education-service-delivery/Progress_reports-variety.md
extra_css:
- stylesheets/extra.css
- assets/css/floating-actions.css
- stylesheets/snake-gallery.css
extra_javascript:
- assets/js/floating-actions.js
